version: '3.8' #https://docs.docker.com/compose/compose-file/compose-versioning/

services:
    vacinaapp:
        image: cleytonferrari/appvacina:latest
        container_name: appvacina
        ports:
            - 8080:80
        depends_on: 
            - 'mongodb'
        networks:
            - vacina-network
            
    mongodb:
        image: "mongo:4.4"
        container_name: mongodbvacina
        restart: unless-stopped
        volumes:
          - 'mongodata:/data'
        ports:
          - '27017:27017'
        networks:
            - vacina-network
            
    caddy: 
        image: caddy:2 
        container_name: caddy
        restart: always 
        depends_on: 
            - 'vacinaapp'
        ports: 
            - 80:80 
            - 443:443 
        volumes: 
            - ./Caddyfile:/etc/caddy/Caddyfile:ro 
            - ./caddy-config:/config 
            - ./caddy-data:/data 
        networks:
            - vacina-network
    
networks:
    vacina-network:
        driver: bridge

volumes:
    mongodata:
        driver_opts:
            type: none
            device: ./database #mkdir -pv database
            o: bind
            

##### Para fazer backup e restore do banco Vacina no MongoDb
## backup ( será salvo no volume mongodata, que esta mapeado para ./database )
#> docker exec -it mongodbvacina mongodump --db Vacina --out /data/backups
## restore
#> docker exec -it mongodbvacina mongorestore /data/backups --drop
